apiVersion: v1
kind: Service
metadata:
  name: k8s-api-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # Change the node port to your desired value
  selector:
    app: k8s-api
