kind: Service
apiVersion: v1
metadata:
  name: k8s-api-service
spec:
  selector:
    app: k8s-api-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-service
spec:
  selector:
    matchLabels:
      app: k8s-api-service
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-api-service
    spec:
      containers:
        - name: k8s-api-service
          image: k8s-api-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: host
